import "./scss/style.scss";
import Header from "@/app/_components/Header";
import Footer from "@/app/_components/Footer";

export const metadata = {
    title: "Create Next App!",
    description: "Generated by create next app",
    robots: {
        index: false,
        follow: false,
    },
};


async function getServices() {
    const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/services`, {
        cache: "no-store", // чтобы всегда свежие данные (или force-cache для кэша)
    });

    if (!res.ok) {
        return []; // fallback
    }

    return res.json();
}

export default async function RootLayout({ children }) {
    const services = await getServices();

    return (
        <html lang="ru">
        <head>
            {process.env.NODE_ENV === 'development' && (
                <>
                    <meta httpEquiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
                    <meta httpEquiv="Pragma" content="no-cache" />
                    <meta httpEquiv="Expires" content="0" />
                </>
            )}
        </head>
        <body className="layout">
        <Header />
        <main className="layout__main">{children}</main>
        <Footer />
        </body>
        </html>
    );
}
